services:
  - type: web
    name: fintech-chatbot
    env: python
    buildCommand: |
      python -m pip install --upgrade pip
      pip install gunicorn
      pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: PORT
        value: 10000
      - key: ENVIRONMENT
        value: production
      - key: FLASK_ENV
        value: production
